//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTTMVCMCSDTY
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batch_Detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Batch_Detail()
        {
            this.Enrollments = new HashSet<Enrollment>();
        }
    
        public long BatchID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public long TrainerID { get; set; }
        public long TrainingModuleID { get; set; }
    
        public virtual Trainer_Detail Trainer_Details { get; set; }
        public virtual Training_Module_Detail Training_Module_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enrollment> Enrollments { get; set; }
    }
}
