//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTTMVCMCSDTY
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        public long ID { get; set; }
        public long BatchID { get; set; }
        public long TraineeID { get; set; }
    
        public virtual Batch_Detail Batch_Details { get; set; }
        public virtual Trainee_Detail Trainee_Details { get; set; }
    }
}
