//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTTMVCMCSDTY
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MVCMCSTYEntities : DbContext
    {
        public MVCMCSTYEntities()
            : base("name=MVCMCSTYEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Batch_Detail> Batch_Details { get; set; }
        public virtual DbSet<Enrollment> Enrollments { get; set; }
        public virtual DbSet<Login_Detail> Login_Details { get; set; }
        public virtual DbSet<Trainee_Detail> Trainee_Details { get; set; }
        public virtual DbSet<Trainer_Detail> Trainer_Details { get; set; }
        public virtual DbSet<Training_Module_Detail> Training_Module_Details { get; set; }
    }
}
