//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTTMVCMCSDTY
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainer_Detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trainer_Detail()
        {
            this.Batch_Details = new HashSet<Batch_Detail>();
        }
    
        public long TrainerID { get; set; }
        public string Name { get; set; }
        public string Skill { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Batch_Detail> Batch_Details { get; set; }
    }
}
